### PR TITLE
api server cannot synthesize text after upgrade latest speech-utils

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by xquanluu** [comment]
Yes it's ready @davehorton

**Comment by davehorton** [comment]
is there already a test case for this?

**Review by davehorton — APPROVED** [review]

**Comment by xquanluu** [comment]
Just added but seem speech credential ENV VARIABLE is not set

**Comment by davehorton** [comment]
> Just added but seem speech credential ENV VARIABLE is not set

There are secrets set for MICROSOFT_API_KEY and MICROSOFT_REGION

**Pull request merged**
