### PR TITLE
Feature/avoid time attacks login | sign in

### PR DESCRIPTION
**Pull request by Catharsis68**
Background:
The response times of `login` and `sign in` allow conclusions to be drawn about the existence of user account during authentication.  e.g. a non-existing user has a faster response time compared to an existing user with correct/incorrect password. 

To avoid these conclusions just from the response time, this PR adds the possibility to add a custom delay to a response.
* class `DelayClient` in the helpers folder to simulate delay in sending a response

* login and signin response time should be in the range of 200-300ms regardless of valid, invalid or missing auth data

Bugfixes:
lib/auth/index.js => fixed wrong name error => err

signin.js
Sending a request with a user that has no connected account_sid was crashing the service. I added a validation

### CODE REVIEW

**Comment by davehorton** [comment]
@xquanluu could you give this a review?

**Comment by xquanluu** [comment]
Hi @davehorton  @Catharsis68  May be I'm wrong but I dont see much value from this feature. as adding 100 or 200ms does not make any differrent.

And Today Database just have 1 row of records, later database have 100k rows or 1m rows, then we have to adjust the response time again.

For me, this feature need to think carefully.

**Comment by Catharsis68** [comment]
@xquanluu  I changed the implementation slightly:

* as soon as `login` or `signin` is hit, a timer starts via performance.now()
* In the DelayClient we can define the desired delay and a random threshold
* depending on the actual process time the delay is calculated

With that approach, it is easiliy possible to adjust the delay in case of larger / longer db queries

**Comment by davehorton** [comment]
@Catharsis68  can you update this to the latest main branch?

**Comment by Catharsis68** [comment]
@davehorton  merged latest main

**Comment by davehorton** [comment]
I feel like the code might be a bit cleaner if we simply handled this in a middleware function, e.g. something like
```js
module.exports = function randomizeLoginResponse(req, res, next) {
   if (['/login', '/signin'].includes(req.path)) {
       const args = this.arguments;
       const temp = res.send;
       res.send = async() => {
          await someRandomDelay;
           temp.apply(args);
      }
   }
   next();
})

..

app.use(randomizeLoginResponse);
```

**Comment by Catharsis68** [comment]
@davehorton  I created a new PR with the middleware approach 
#146

**Pull request closed without merging**
